#!/bin/bash

green=$(tput setaf 40);
red=$(tput setaf 196);
blue=$(tput setaf 4);
orange=$(tput setaf 178);
orangeRed=$(tput setaf 202);
magenta=$(tput setaf 129);
grey=$(tput setaf 250);
bold=$(tput bold);
reset=$(tput sgr0);

g++ gen.cpp -o gen
# rn $1 
g++ -std=c++17 $1.cpp -o $1
g++ $2.cpp -o $2

passed=0

for (( c=1 ; c <= 1000 ; c++ ))
do
    echo -n "${blue}Test #$c: "
    ./gen $c > inp
    ./$1 < inp > out1
    ./$2 < inp > out2
    diff -w out1 out2 > diff.txt
    if [ $? -ne 0 ]
    then
        echo "${red}Failed"
        echo "${blue}${orangeRed}----------Input----------${reset}"
        cat inp
        echo""
        echo "${blue}${orangeRed}----------Output---------${reset}"
        cat out1 
        echo""
        echo "${blue}${orangeRed}---------Accepted--------${reset}"
        cat out2
        echo ""
        echo "${blue}${orangeRed}-----------Diff----------${reset}"
        diff --color out1 out2
        break
    else 
        echo "${green}Passed${reset}"
        ((passed=passed+1))
    fi
done

echo ""
echo "${green}${bold}Passed : ${grey}$passed${reset}"



