name : Github Action demo
on : [push]
jobs:
    Explore:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v5
          with:
            python-version: '3.13' 
        - run: python a.py